# Generated by Django 4.2.2 on 2023-08-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
    ]
