# Generated by Django 4.2.2 on 2023-08-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_teacherprofile_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="balance",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
