# Generated by Django 4.2.2 on 2023-08-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_teacherprofile_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherprofile",
            name="balance",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
