# Generated by Django 4.2.7 on 2024-01-16 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sectionitems", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionitem",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="sectionitem",
            name="object_id",
        ),
        migrations.AddField(
            model_name="sectionitem",
            name="additional_file",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sectionitems.additionalfile",
            ),
        ),
        migrations.AddField(
            model_name="sectionitem",
            name="homework",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sectionitems.homework",
            ),
        ),
        migrations.AddField(
            model_name="sectionitem",
            name="lesson",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sectionitems.lesson",
            ),
        ),
        migrations.AddField(
            model_name="sectionitem",
            name="test",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sectionitems.test",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectionitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("lesson__isnull", False),
                        ("additional_file__isnull", True),
                        ("test__isnull", True),
                        ("homework__isnull", True),
                    ),
                    models.Q(
                        ("lesson__isnull", True),
                        ("additional_file__isnull", False),
                        ("test__isnull", True),
                        ("homework__isnull", True),
                    ),
                    models.Q(
                        ("lesson__isnull", True),
                        ("additional_file__isnull", True),
                        ("test__isnull", False),
                        ("homework__isnull", True),
                    ),
                    models.Q(
                        ("lesson__isnull", True),
                        ("additional_file__isnull", True),
                        ("test__isnull", True),
                        ("homework__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="only_one_not_null",
            ),
        ),
    ]
