# Generated by Django 4.2.7 on 2024-01-16 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0021_remove_homework_section_remove_lesson_section_and_more"),
        ("sectionitems", "0002_remove_sectionitem_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalfile",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.section"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.section"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.section"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.section"
            ),
        ),
    ]
