# Generated by Django 4.2.7 on 2024-02-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sectionitems",
            "0003_alter_additionalfile_section_alter_homework_section_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalfile",
            name="option",
            field=models.CharField(
                choices=[
                    ("free", "Free: it is a free content"),
                    ("basic", "Basic: all the basic content"),
                    ("extra", "Extra: some additional files"),
                    ("premium", "Premium: all the content you need"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="option",
            field=models.CharField(
                choices=[
                    ("free", "Free: it is a free content"),
                    ("basic", "Basic: all the basic content"),
                    ("extra", "Extra: some additional files"),
                    ("premium", "Premium: all the content you need"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="option",
            field=models.CharField(
                choices=[
                    ("free", "Free: it is a free content"),
                    ("basic", "Basic: all the basic content"),
                    ("extra", "Extra: some additional files"),
                    ("premium", "Premium: all the content you need"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="option",
            field=models.CharField(
                choices=[
                    ("free", "Free: it is a free content"),
                    ("basic", "Basic: all the basic content"),
                    ("extra", "Extra: some additional files"),
                    ("premium", "Premium: all the content you need"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
    ]
