# Generated by Django 4.2.7 on 2024-03-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0029_alter_course_options"),
        (
            "sectionitems",
            "0004_alter_additionalfile_option_alter_homework_option_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.section",
            ),
        ),
    ]
