# Generated by Django 4.2.7 on 2024-01-11 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_name_alter_subcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, message="Количество символов должно быть больше 4"
                    ),
                    django.core.validators.RegexValidator(
                        "^[А-Яа-я\\-]+$",
                        message="Допускаются только кириллические буквы",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, message="Количество символов должно быть больше 4"
                    ),
                    django.core.validators.RegexValidator(
                        "^[А-Яа-я\\-]+$",
                        message="Допускаются только кириллические буквы",
                    ),
                ],
            ),
        ),
    ]
