# Generated by Django 4.2.2 on 2023-06-20 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cover",
            field=models.ImageField(default="1.jpg", upload_to="media/courses/covers/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="date_created",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(2023, 6, 20, 19, 6, 57, 561238),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="date_updated",
            field=models.DateField(
                auto_now=True, default=datetime.datetime(2023, 6, 20, 19, 7, 10, 969012)
            ),
            preserve_default=False,
        ),
    ]
