# Generated by Django 4.2.2 on 2023-06-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_test_testquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="testquestion",
            name="question",
            field=models.CharField(default="Question", max_length=180),
            preserve_default=False,
        ),
    ]
