# Generated by Django 4.2.2 on 2023-06-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_homework"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionitem",
            name="option",
            field=models.CharField(
                choices=[
                    ("basic", "All the basic content"),
                    ("extra", "Some additional files"),
                    ("premium", "All the content you need"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
    ]
