# Generated by Django 4.2.2 on 2023-07-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_sectionitem_option"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionitem",
            name="option",
        ),
        migrations.AddField(
            model_name="additionalfile",
            name="option",
            field=models.CharField(
                choices=[
                    ("basic", "All the basic content"),
                    ("extra", "Some additional files"),
                    ("premium", "All the content you need"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="option",
            field=models.CharField(
                choices=[
                    ("basic", "All the basic content"),
                    ("extra", "Some additional files"),
                    ("premium", "All the content you need"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="option",
            field=models.CharField(
                choices=[
                    ("basic", "All the basic content"),
                    ("extra", "Some additional files"),
                    ("premium", "All the content you need"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="option",
            field=models.CharField(
                choices=[
                    ("basic", "All the basic content"),
                    ("extra", "Some additional files"),
                    ("premium", "All the content you need"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
    ]
