# Generated by Django 4.2.2 on 2023-07-03 15:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_remove_sectionitem_option_additionalfile_option_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="what_will_learn",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=120), size=20
            ),
        ),
    ]
