# Generated by Django 4.2.2 on 2023-07-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_alter_course_what_will_learn"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=300)),
                ("price", models.CharField(max_length=300)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe",
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
