# Generated by Django 4.2.2 on 2023-08-14 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_name_alter_subcategory_name"),
        ("courses", "0015_lesson_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="categories.subject",
            ),
        ),
    ]
