# Generated by Django 4.2.7 on 2024-01-11 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0020_remove_testcompletion_course_testcompletion_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="section",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="section",
        ),
        migrations.RemoveField(
            model_name="sectionitem",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="sectionitem",
            name="section",
        ),
        migrations.RemoveField(
            model_name="test",
            name="section",
        ),
        migrations.RemoveField(
            model_name="testcompletion",
            name="student",
        ),
        migrations.RemoveField(
            model_name="testcompletion",
            name="test",
        ),
        migrations.RemoveField(
            model_name="testquestion",
            name="test",
        ),
        migrations.DeleteModel(
            name="AdditionalFile",
        ),
        migrations.DeleteModel(
            name="Homework",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
        migrations.DeleteModel(
            name="SectionItem",
        ),
        migrations.DeleteModel(
            name="Test",
        ),
        migrations.DeleteModel(
            name="TestCompletion",
        ),
        migrations.DeleteModel(
            name="TestQuestion",
        ),
    ]
