# Generated by Django 4.2.7 on 2024-01-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0023_remove_course_options_alter_courseprice_stripe"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(max_length=160, null=True, unique=True),
        ),
    ]
