# Generated by Django 4.2.7 on 2024-02-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0024_course_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner level"),
                    ("advanced", "Advanced level"),
                    ("expert", "Expert level"),
                ],
                default="beginner",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="coursepayment",
            name="option",
            field=models.CharField(
                choices=[
                    ("free", "Free: it is a free content"),
                    ("basic", "Basic: all the basic content"),
                    ("extra", "Extra: some additional files"),
                    ("premium", "Premium: all the content you need"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="courseprice",
            name="option",
            field=models.CharField(
                choices=[
                    ("free", "Free: it is a free content"),
                    ("basic", "Basic: all the basic content"),
                    ("extra", "Extra: some additional files"),
                    ("premium", "Premium: all the content you need"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
    ]
