# Generated by Django 4.2.7 on 2024-03-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0025_course_level_alter_coursepayment_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
