# Generated by Django 4.2.7 on 2024-03-18 16:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0026_course_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="sectionitems_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=24), default=[], size=12
            ),
            preserve_default=False,
        ),
    ]
