# Generated by Django 4.2.7 on 2024-03-18 18:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0028_rename_sectionitems_types_course_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=24), null=True, size=12
            ),
        ),
    ]
