COURSE_PAYMENT_PAID = 'paid'
COURSE_PAYMENT_NOT_PAID = 'not paid'
COURSE_PAYMENT_ERROR= 'error'
COURSE_PAYMENT_REFUND = 'refund'

COURSE_OPTION_FREE = 'free'
COURSE_OPTION_BASIC = 'basic'
COURSE_OPTION_EXTRA = 'extra'
COURSE_OPTION_PREMIUM = 'premium'
COURSE_OPTIONS = [COURSE_OPTION_FREE, COURSE_OPTION_BASIC, COURSE_OPTION_EXTRA, COURSE_OPTION_PREMIUM]